id: A553BBAF8
title: Colophon
type: translation
source_metadata:
  languages:
  - bo
  - zh
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:28:54.766527
  last_modified_at: 2022-03-01 21:28:54.766535
